const negocios = [
  {
    id: 'la-cafetera',
    nombre: 'La Cafetera',
    categoria: 'Café',
    logo: 'assets/negocios/la-cafetera/Cafetera.jpeg',
    menu: 'assets/negocios/la-cafetera/menu-01.jpg',
    tipo: 'imagen',
  },
  {
    id: 'dejamu',
    nombre: 'Dejamu',
    categoria: 'Fusión',
    logo: 'assets/negocios/dejamu/image_495.png',
    menu: 'assets/negocios/dejamu/menu-01.jpg',
    tipo: 'imagen',
  },
  {
    id: 'satomi-bento',
    nombre: 'Satomi Bento',
    categoria: 'Japonés',
    logo: 'assets/negocios/satomi-bento/SATOMI-1.png',
    menu: 'https://menupp.co/satomibento',
    tipo: 'externo',
  },
  {
    id: 'cafe-pintado',
    nombre: 'Café Pintado',
    categoria: 'Café',
    logo: 'assets/negocios/cafe-pintado/images.png',
    menu: 'assets/negocios/cafe-pintado/menu-01.jpg',
    tipo: 'imagen',
  },
  {
    id: 'el-obelisco',
    nombre: 'Obelisco',
    categoria: 'Caleño',
    logo: 'assets/negocios/el-obelisco/Elobelisco.jpg',
    menu: 'https://menupp.co/obeliscodeli/venue/15b835df-6bdd-490f-93a3-82ab0387ee16/menu/43286df3-bfc0-48a9-832d-8db80a8e8621',
    tipo: 'externo',
  },
  {
    id: 'el-bochinche',
    nombre: 'El Bochinche',
    categoria: 'Colombiano',
    logo: 'assets/negocios/el-bochinche/images.jpg',
    menu: [
      'assets/negocios/el-bochinche/menu-01.jpg',
      'assets/negocios/el-bochinche/menu-02.jpg',
    ],
    tipo: 'imagen',
  },
  {
    id: 'cali-coffee-tour',
    nombre: 'Cali Coffee Tour',
    categoria: 'Café',
    destacado: true,
    logo: 'assets/negocios/cali-coffee-tour/images.jpg',
    menu: 'https://menupp.co/coffeemaster/venue/nu9KOuY1SXmbrxiFVKKL/menu/6f3a7cb9-74f9-4792-af2e-68527d230006',
    tipo: 'externo',
  },
  {
    id: 'sabor-peruano',
    nombre: 'Sabor Peruano',
    categoria: 'Peruano',
    logo: 'assets/negocios/sabor-peruano/logo.jpg',
    menu: 'assets/negocios/sabor-peruano/menu-01.jpg',
    tipo: 'imagen',
  },
  {
    id: 'uepa-ve',
    nombre: "Mirá! Uepa'Ve",
    categoria: 'Wraps & Arepas',
    logo: 'assets/negocios/uepa-ve/Mira ve.png',
    menu: [
      'assets/negocios/uepa-ve/menu-01.jpg',
      'assets/negocios/uepa-ve/menu-02.jpg',
      'assets/negocios/uepa-ve/menu-03.jpg',
    ],
    tipo: 'imagen',
  },
  {
    id: 'bandeja-coreana',
    nombre: 'Bandeja Coreana',
    categoria: 'Coreano',
    logo: 'assets/negocios/bandeja-coreana/logo.jpg',
    menu: [
      'assets/negocios/bandeja-coreana/menu-01.jpg',
      'assets/negocios/bandeja-coreana/menu-02.jpg',
      'assets/negocios/bandeja-coreana/menu-03.jpg',
    ],
    tipo: 'imagen',
  },
  {
    id: 'monster-park',
    nombre: 'Monster Park',
    categoria: 'Entretenimiento',
    logo: 'assets/negocios/monster-park/logo.jpeg',
    menu: 'assets/negocios/monster-park/menu-01.jpg',
    tipo: 'imagen',
  },
];
